
// Mock data for Skill Swap Connect

export const skillTags = [
  "JavaScript", "Python", "Guitar", "Excel", "IELTS", "French", "Yoga",
  "Photography", "UI Design", "Public Speaking", "Spanish", "React",
  "Data Analysis", "Piano", "Chinese", "Cooking", "Video Editing",
  "Marketing", "Accounting", "Personal Training", "Web Design", "SEO"
];

export const skillCategories = [
  { name: "Technology", tags: ["JavaScript", "Python", "React", "Web Design"], icon: "💻" },
  { name: "Languages", tags: ["IELTS", "French", "Spanish", "Chinese"], icon: "🌍" },
  { name: "Design", tags: ["UI Design", "Photography", "Video Editing"], icon: "🎨" },
  { name: "Music", tags: ["Guitar", "Piano"], icon: "🎵" },
  { name: "Fitness", tags: ["Yoga", "Personal Training"], icon: "💪" },
  { name: "Business", tags: ["Excel", "Marketing", "SEO", "Accounting"], icon: "💼" },
];

export interface UserProfile {
  id: string;
  name: string;
  avatar: string;
  location: string;
  rating: number;
  totalSessions: number;
  bio: string;
  offerSkills: Array<{
    skill: string;
    level: "Cơ Bản" | "Trung Cấp" | "Nâng Cao";
    mode: "Online" | "Offline" | "Both";
  }>;
  wantSkills: string[];
  availability: string;
  joinedDate: string;
}

export const mockUsers: UserProfile[] = [
  {
    id: "u1",
    name: "Nguyễn Hương Giang",
    avatar: "👩‍💻",
    location: "Hà Nội",
    rating: 4.9,
    totalSessions: 47,
    bio: "Lập trình viên full-stack đam mê giảng dạy công nghệ web. Yêu thích học ngoại ngữ!",
    offerSkills: [
      { skill: "JavaScript", level: "Nâng Cao", mode: "Both" },
      { skill: "React", level: "Nâng Cao", mode: "Online" },
      { skill: "Python", level: "Trung Cấp", mode: "Online" },
    ],
    wantSkills: ["Spanish", "Guitar", "Photography"],
    availability: "Tối thứ 2-6 từ 19h-21h, Thứ 7",
    joinedDate: "2024-01-15",
  },
  {
    id: "u2",
    name: "Trần Minh Quân",
    avatar: "🎸",
    location: "TP. Hồ Chí Minh",
    rating: 4.8,
    totalSessions: 62,
    bio: "Guitarist chuyên nghiệp với 15 năm kinh nghiệm. Thông thạo tiếng Tây Ban Nha và thích giúp mọi người giao tiếp tốt hơn!",
    offerSkills: [
      { skill: "Guitar", level: "Nâng Cao", mode: "Both" },
      { skill: "Spanish", level: "Nâng Cao", mode: "Online" },
      { skill: "Public Speaking", level: "Trung Cấp", mode: "Online" },
    ],
    wantSkills: ["Video Editing", "Marketing", "Web Design"],
    availability: "Linh hoạt trong tuần",
    joinedDate: "2023-11-20",
  },
  {
    id: "u3",
    name: "Lê Thảo Vy",
    avatar: "🧘‍♀️",
    location: "Đà Nẵng",
    rating: 5.0,
    totalSessions: 38,
    bio: "Huấn luyện viên yoga được chứng nhận và chuyên gia sức khỏe. Cũng đam mê phân tích dữ liệu và Excel!",
    offerSkills: [
      { skill: "Yoga", level: "Nâng Cao", mode: "Both" },
      { skill: "Excel", level: "Nâng Cao", mode: "Online" },
      { skill: "Data Analysis", level: "Trung Cấp", mode: "Online" },
    ],
    wantSkills: ["Photography", "UI Design", "French"],
    availability: "Sáng sớm và cuối tuần",
    joinedDate: "2024-02-10",
  },
  {
    id: "u4",
    name: "Phạm Tuấn Anh",
    avatar: "📸",
    location: "Cần Thơ",
    rating: 4.7,
    totalSessions: 29,
    bio: "Nhiếp ảnh gia chuyên nghiệp chuyên chụp chân dung. Người bản ngữ tiếng Trung háo hức chia sẻ!",
    offerSkills: [
      { skill: "Photography", level: "Nâng Cao", mode: "Both" },
      { skill: "Chinese", level: "Nâng Cao", mode: "Online" },
      { skill: "Video Editing", level: "Trung Cấp", mode: "Online" },
    ],
    wantSkills: ["Python", "SEO", "Piano"],
    availability: "Chiều và tối",
    joinedDate: "2023-12-05",
  },
  {
    id: "u5",
    name: "Đỗ Thu Hằng",
    avatar: "🎨",
    location: "Hải Phòng",
    rating: 4.9,
    totalSessions: 54,
    bio: "Nhà thiết kế UI/UX với 8 năm kinh nghiệm. Yêu nấu ăn và chia sẻ công thức từ khắp nơi trên thế giới!",
    offerSkills: [
      { skill: "UI Design", level: "Nâng Cao", mode: "Online" },
      { skill: "Web Design", level: "Nâng Cao", mode: "Online" },
      { skill: "Cooking", level: "Trung Cấp", mode: "Offline" },
    ],
    wantSkills: ["JavaScript", "IELTS", "Personal Training"],
    availability: "Tối thứ 2-6 sau 18h",
    joinedDate: "2024-01-08",
  },
  {
    id: "u6",
    name: "Vũ Đức Long",
    avatar: "💼",
    location: "Nha Trang",
    rating: 4.6,
    totalSessions: 41,
    bio: "Chuyên gia tư vấn marketing và bậc thầy Excel. Luôn muốn mở rộng kỹ năng ngoại ngữ!",
    offerSkills: [
      { skill: "Marketing", level: "Nâng Cao", mode: "Online" },
      { skill: "Excel", level: "Nâng Cao", mode: "Online" },
      { skill: "SEO", level: "Trung Cấp", mode: "Online" },
    ],
    wantSkills: ["French", "Accounting", "Piano"],
    availability: "Cuối tuần và tối thứ 2",
    joinedDate: "2023-10-18",
  },
  // Expanded profiles with diverse ratings from 2.0 to 5.0
  {
    id: "u7",
    name: "Hoàng Minh Tuấn",
    avatar: "🎵",
    location: "Hà Nội",
    rating: 4.8,
    totalSessions: 35,
    bio: "Pianist cổ điển với 12 năm kinh nghiệm biểu diễn. Đam mê chia sẻ kiến thức âm nhạc!",
    offerSkills: [
      { skill: "Piano", level: "Nâng Cao", mode: "Both" },
      { skill: "Music Theory", level: "Nâng Cao", mode: "Online" },
    ],
    wantSkills: ["Web Design", "Data Analysis", "French"],
    availability: "Tối thứ 3-5, Sáng thứ 7",
    joinedDate: "2024-03-01",
  },
  {
    id: "u8",
    name: "Nguyễn Thị Lan",
    avatar: "📚",
    location: "TP. Hồ Chí Minh",
    rating: 4.5,
    totalSessions: 28,
    bio: "Giáo viên IELTS với 8 năm kinh nghiệm. Đã giúp hàng trăm học viên đạt điểm cao!",
    offerSkills: [
      { skill: "IELTS", level: "Nâng Cao", mode: "Both" },
      { skill: "English", level: "Nâng Cao", mode: "Online" },
    ],
    wantSkills: ["Yoga", "Cooking", "Photography"],
    availability: "Sáng thứ 2-6, Tối thứ 3-5",
    joinedDate: "2024-02-15",
  },
  {
    id: "u9",
    name: "Trần Văn Hải",
    avatar: "💪",
    location: "Đà Nẵng",
    rating: 4.7,
    totalSessions: 42,
    bio: "Huấn luyện viên thể hình chuyên nghiệp. Chuyên về tập luyện sức mạnh và dinh dưỡng!",
    offerSkills: [
      { skill: "Personal Training", level: "Nâng Cao", mode: "Offline" },
      { skill: "Fitness", level: "Nâng Cao", mode: "Both" },
    ],
    wantSkills: ["Spanish", "Video Editing", "SEO"],
    availability: "Sáng 6h-9h, Chiều 16h-20h",
    joinedDate: "2023-12-20",
  },
  {
    id: "u10",
    name: "Lê Thị Mai",
    avatar: "🍳",
    location: "Cần Thơ",
    rating: 4.4,
    totalSessions: 23,
    bio: "Đầu bếp chuyên về ẩm thực Việt Nam. Yêu thích chia sẻ bí quyết nấu ăn truyền thống!",
    offerSkills: [
      { skill: "Cooking", level: "Nâng Cao", mode: "Offline" },
      { skill: "Vietnamese Cuisine", level: "Nâng Cao", mode: "Both" },
    ],
    wantSkills: ["Excel", "Marketing", "Public Speaking"],
    availability: "Cuối tuần, Tối thứ 4-6",
    joinedDate: "2024-01-25",
  },
  {
    id: "u11",
    name: "Phạm Quang Huy",
    avatar: "🎬",
    location: "Hải Phòng",
    rating: 4.6,
    totalSessions: 31,
    bio: "Editor video chuyên nghiệp với 6 năm kinh nghiệm. Thành thạo Adobe Premiere và After Effects!",
    offerSkills: [
      { skill: "Video Editing", level: "Nâng Cao", mode: "Online" },
      { skill: "Motion Graphics", level: "Trung Cấp", mode: "Online" },
    ],
    wantSkills: ["Chinese", "Guitar", "Data Analysis"],
    availability: "Linh hoạt, chủ yếu buổi tối",
    joinedDate: "2024-02-28",
  },
  {
    id: "u12",
    name: "Đặng Thùy Linh",
    avatar: "🗣️",
    location: "Nha Trang",
    rating: 4.9,
    totalSessions: 45,
    bio: "Chuyên gia đào tạo kỹ năng thuyết trình và giao tiếp. Đã huấn luyện cho nhiều doanh nghiệp lớn!",
    offerSkills: [
      { skill: "Public Speaking", level: "Nâng Cao", mode: "Both" },
      { skill: "Communication", level: "Nâng Cao", mode: "Online" },
    ],
    wantSkills: ["Python", "UI Design", "Yoga"],
    availability: "Tối thứ 2-4-6, Sáng thứ 7",
    joinedDate: "2023-11-15",
  },
  {
    id: "u13",
    name: "Vũ Minh Đức",
    avatar: "📊",
    location: "Hà Nội",
    rating: 4.3,
    totalSessions: 19,
    bio: "Chuyên viên phân tích dữ liệu với kinh nghiệm trong ngành tài chính. Thành thạo Python và SQL!",
    offerSkills: [
      { skill: "Data Analysis", level: "Nâng Cao", mode: "Online" },
      { skill: "Python", level: "Trung Cấp", mode: "Online" },
    ],
    wantSkills: ["French", "Photography", "Guitar"],
    availability: "Tối thứ 2-6 từ 20h-22h",
    joinedDate: "2024-03-10",
  },
  {
    id: "u14",
    name: "Ngô Thị Hương",
    avatar: "🌍",
    location: "TP. Hồ Chí Minh",
    rating: 4.7,
    totalSessions: 37,
    bio: "Giáo viên tiếng Pháp bản ngữ với 10 năm kinh nghiệm. Phương pháp dạy hiện đại và hiệu quả!",
    offerSkills: [
      { skill: "French", level: "Nâng Cao", mode: "Both" },
      { skill: "Language Teaching", level: "Nâng Cao", mode: "Online" },
    ],
    wantSkills: ["React", "Excel", "Personal Training"],
    availability: "Sáng thứ 2-5, Tối thứ 3-6",
    joinedDate: "2023-12-10",
  },
  {
    id: "u15",
    name: "Bùi Văn Tài",
    avatar: "💻",
    location: "Đà Nẵng",
    rating: 4.2,
    totalSessions: 16,
    bio: "Lập trình viên front-end chuyên về React và Vue.js. Thích chia sẻ kinh nghiệm phát triển web!",
    offerSkills: [
      { skill: "React", level: "Nâng Cao", mode: "Online" },
      { skill: "JavaScript", level: "Trung Cấp", mode: "Online" },
    ],
    wantSkills: ["Spanish", "Photography", "Cooking"],
    availability: "Tối thứ 2-4-6 từ 19h-21h",
    joinedDate: "2024-03-15",
  },
  {
    id: "u16",
    name: "Trịnh Thị Ngọc",
    avatar: "📈",
    location: "Cần Thơ",
    rating: 4.8,
    totalSessions: 52,
    bio: "Chuyên gia kế toán với 15 năm kinh nghiệm. Thành thạo các phần mềm kế toán và Excel nâng cao!",
    offerSkills: [
      { skill: "Accounting", level: "Nâng Cao", mode: "Online" },
      { skill: "Excel", level: "Nâng Cao", mode: "Online" },
    ],
    wantSkills: ["UI Design", "Public Speaking", "Yoga"],
    availability: "Tối thứ 2-6, Sáng thứ 7",
    joinedDate: "2023-11-05",
  },
  {
    id: "u17",
    name: "Lý Văn Sơn",
    avatar: "🎨",
    location: "Hải Phòng",
    rating: 4.1,
    totalSessions: 14,
    bio: "Designer đồ họa tự do với 4 năm kinh nghiệm. Chuyên về thiết kế logo và branding!",
    offerSkills: [
      { skill: "UI Design", level: "Trung Cấp", mode: "Online" },
      { skill: "Graphic Design", level: "Trung Cấp", mode: "Online" },
    ],
    wantSkills: ["Python", "Data Analysis", "French"],
    availability: "Linh hoạt, ưu tiên buổi tối",
    joinedDate: "2024-03-20",
  },
  {
    id: "u18",
    name: "Đinh Thị Hoa",
    avatar: "🧘‍♀️",
    location: "Nha Trang",
    rating: 4.9,
    totalSessions: 48,
    bio: "Huấn luyện viên yoga trị liệu. Chuyên về yoga cho người mới bắt đầu và phục hồi chấn thương!",
    offerSkills: [
      { skill: "Yoga", level: "Nâng Cao", mode: "Both" },
      { skill: "Meditation", level: "Trung Cấp", mode: "Online" },
    ],
    wantSkills: ["Web Design", "SEO", "Chinese"],
    availability: "Sáng sớm 5h-7h, Tối 19h-21h",
    joinedDate: "2024-01-20",
  },
  {
    id: "u19",
    name: "Mai Văn Phong",
    avatar: "📸",
    location: "Hà Nội",
    rating: 4.0,
    totalSessions: 12,
    bio: "Nhiếp ảnh gia phong cảnh với 3 năm kinh nghiệm. Đam mê chụp ảnh thiên nhiên và kiến trúc!",
    offerSkills: [
      { skill: "Photography", level: "Trung Cấp", mode: "Offline" },
      { skill: "Photo Editing", level: "Cơ Bản", mode: "Online" },
    ],
    wantSkills: ["Excel", "Marketing", "Public Speaking"],
    availability: "Cuối tuần, Sáng thứ 7",
    joinedDate: "2024-03-25",
  },
  {
    id: "u20",
    name: "Nguyễn Thị Thu",
    avatar: "🎵",
    location: "TP. Hồ Chí Minh",
    rating: 4.6,
    totalSessions: 33,
    bio: "Giáo viên guitar acoustic với 7 năm kinh nghiệm. Chuyên dạy nhạc pop và ballad!",
    offerSkills: [
      { skill: "Guitar", level: "Nâng Cao", mode: "Both" },
      { skill: "Music Theory", level: "Trung Cấp", mode: "Online" },
    ],
    wantSkills: ["UI Design", "Data Analysis", "French"],
    availability: "Tối thứ 2-4-6 từ 18h-20h",
    joinedDate: "2024-01-30",
  },
  {
    id: "u21",
    name: "Trần Văn Bình",
    avatar: "💼",
    location: "Đà Nẵng",
    rating: 3.8,
    totalSessions: 8,
    bio: "Chuyên viên SEO mới vào nghề. Đam mê tối ưu hóa website và content marketing!",
    offerSkills: [
      { skill: "SEO", level: "Cơ Bản", mode: "Online" },
      { skill: "Content Writing", level: "Cơ Bản", mode: "Online" },
    ],
    wantSkills: ["JavaScript", "Excel", "Photography"],
    availability: "Tối thứ 3-5, Sáng thứ 7",
    joinedDate: "2024-04-01",
  },
  {
    id: "u22",
    name: "Lê Thị Hồng",
    avatar: "🧘‍♀️",
    location: "Cần Thơ",
    rating: 4.9,
    totalSessions: 56,
    bio: "Huấn luyện viên yoga prenatal. Chuyên về yoga cho bà bầu và phụ nữ sau sinh!",
    offerSkills: [
      { skill: "Yoga", level: "Nâng Cao", mode: "Both" },
      { skill: "Prenatal Yoga", level: "Nâng Cao", mode: "Offline" },
    ],
    wantSkills: ["Web Design", "Chinese", "Video Editing"],
    availability: "Sáng thứ 2-6 từ 7h-9h",
    joinedDate: "2023-11-25",
  },
  {
    id: "u23",
    name: "Phạm Văn Cường",
    avatar: "📊",
    location: "Hải Phòng",
    rating: 4.4,
    totalSessions: 25,
    bio: "Chuyên viên phân tích dữ liệu trong ngành bán lẻ. Thành thạo Power BI và SQL!",
    offerSkills: [
      { skill: "Data Analysis", level: "Trung Cấp", mode: "Online" },
      { skill: "Power BI", level: "Trung Cấp", mode: "Online" },
    ],
    wantSkills: ["Spanish", "Guitar", "Cooking"],
    availability: "Tối thứ 2-6 từ 19h-21h",
    joinedDate: "2024-02-20",
  },
  {
    id: "u24",
    name: "Đỗ Thị Ngọc",
    avatar: "🌍",
    location: "Nha Trang",
    rating: 4.7,
    totalSessions: 41,
    bio: "Giáo viên tiếng Trung với 9 năm kinh nghiệm. Phương pháp dạy sinh động và thực tế!",
    offerSkills: [
      { skill: "Chinese", level: "Nâng Cao", mode: "Both" },
      { skill: "Mandarin", level: "Nâng Cao", mode: "Online" },
    ],
    wantSkills: ["React", "Excel", "Personal Training"],
    availability: "Sáng thứ 3-5-7, Tối thứ 2-4",
    joinedDate: "2023-12-15",
  },
  {
    id: "u25",
    name: "Vũ Minh Tuấn",
    avatar: "💻",
    location: "Hà Nội",
    rating: 4.1,
    totalSessions: 15,
    bio: "Lập trình viên Python với 2 năm kinh nghiệm. Đam mê machine learning và AI!",
    offerSkills: [
      { skill: "Python", level: "Trung Cấp", mode: "Online" },
      { skill: "Machine Learning", level: "Cơ Bản", mode: "Online" },
    ],
    wantSkills: ["French", "Photography", "Public Speaking"],
    availability: "Tối thứ 2-4-6 từ 20h-22h",
    joinedDate: "2024-03-05",
  },
  {
    id: "u26",
    name: "Nguyễn Thị Hà",
    avatar: "📚",
    location: "TP. Hồ Chí Minh",
    rating: 4.8,
    totalSessions: 49,
    bio: "Giáo viên tiếng Anh giao tiếp với 11 năm kinh nghiệm. Chuyên dạy phát âm chuẩn!",
    offerSkills: [
      { skill: "English", level: "Nâng Cao", mode: "Both" },
      { skill: "Pronunciation", level: "Nâng Cao", mode: "Online" },
    ],
    wantSkills: ["Yoga", "Cooking", "UI Design"],
    availability: "Sáng thứ 2-6, Tối thứ 3-5",
    joinedDate: "2023-10-25",
  },
  {
    id: "u27",
    name: "Trần Văn Dũng",
    avatar: "💪",
    location: "Đà Nẵng",
    rating: 4.5,
    totalSessions: 29,
    bio: "Huấn luyện viên calisthenics. Chuyên về tập luyện với trọng lượng cơ thể!",
    offerSkills: [
      { skill: "Personal Training", level: "Nâng Cao", mode: "Offline" },
      { skill: "Calisthenics", level: "Nâng Cao", mode: "Both" },
    ],
    wantSkills: ["Spanish", "Video Editing", "Data Analysis"],
    availability: "Sáng 6h-8h, Chiều 17h-19h",
    joinedDate: "2024-01-10",
  },
  {
    id: "u28",
    name: "Lê Thị Nga",
    avatar: "🍳",
    location: "Cần Thơ",
    rating: 4.3,
    totalSessions: 21,
    bio: "Đầu bếp chuyên về ẩm thực chay. Yêu thích chia sẻ công thức healthy và bổ dưỡng!",
    offerSkills: [
      { skill: "Cooking", level: "Trung Cấp", mode: "Offline" },
      { skill: "Vegetarian Cuisine", level: "Trung Cấp", mode: "Both" },
    ],
    wantSkills: ["Excel", "Marketing", "Web Design"],
    availability: "Cuối tuần, Tối thứ 4-6",
    joinedDate: "2024-02-05",
  },
  {
    id: "u29",
    name: "Phạm Quang Minh",
    avatar: "🎬",
    location: "Hải Phòng",
    rating: 4.6,
    totalSessions: 34,
    bio: "Editor video chuyên về content YouTube. Thành thạo Premiere Pro và DaVinci Resolve!",
    offerSkills: [
      { skill: "Video Editing", level: "Nâng Cao", mode: "Online" },
      { skill: "YouTube Content", level: "Trung Cấp", mode: "Online" },
    ],
    wantSkills: ["Chinese", "Guitar", "SEO"],
    availability: "Linh hoạt, chủ yếu buổi tối",
    joinedDate: "2024-01-15",
  },
  {
    id: "u30",
    name: "Đặng Văn Hùng",
    avatar: "🗣️",
    location: "Nha Trang",
    rating: 4.9,
    totalSessions: 58,
    bio: "Chuyên gia đào tạo kỹ năng đàm phán. Đã huấn luyện cho nhiều doanh nghiệp lớn!",
    offerSkills: [
      { skill: "Public Speaking", level: "Nâng Cao", mode: "Both" },
      { skill: "Negotiation", level: "Nâng Cao", mode: "Online" },
    ],
    wantSkills: ["Python", "UI Design", "Yoga"],
    availability: "Tối thứ 2-4-6, Sáng thứ 7",
    joinedDate: "2023-11-10",
  },
  {
    id: "u31",
    name: "Vũ Thị Lan",
    avatar: "📊",
    location: "Hà Nội",
    rating: 3.9,
    totalSessions: 11,
    bio: "Chuyên viên phân tích dữ liệu trong ngành giáo dục. Thành thạo Excel và Google Sheets!",
    offerSkills: [
      { skill: "Data Analysis", level: "Cơ Bản", mode: "Online" },
      { skill: "Excel", level: "Trung Cấp", mode: "Online" },
    ],
    wantSkills: ["French", "Photography", "Guitar"],
    availability: "Tối thứ 2-6 từ 20h-22h",
    joinedDate: "2024-03-12",
  },
  {
    id: "u32",
    name: "Ngô Văn Hải",
    avatar: "🌍",
    location: "TP. Hồ Chí Minh",
    rating: 4.7,
    totalSessions: 39,
    bio: "Giáo viên tiếng Tây Ban Nha bản ngữ với 8 năm kinh nghiệm. Phương pháp dạy hiện đại!",
    offerSkills: [
      { skill: "Spanish", level: "Nâng Cao", mode: "Both" },
      { skill: "Language Teaching", level: "Nâng Cao", mode: "Online" },
    ],
    wantSkills: ["React", "Excel", "Personal Training"],
    availability: "Sáng thứ 2-5, Tối thứ 3-6",
    joinedDate: "2023-12-08",
  },
  {
    id: "u33",
    name: "Bùi Thị Mai",
    avatar: "💻",
    location: "Đà Nẵng",
    rating: 4.2,
    totalSessions: 17,
    bio: "Lập trình viên JavaScript với 3 năm kinh nghiệm. Đam mê phát triển web và mobile!",
    offerSkills: [
      { skill: "JavaScript", level: "Trung Cấp", mode: "Online" },
      { skill: "React Native", level: "Cơ Bản", mode: "Online" },
    ],
    wantSkills: ["Spanish", "Photography", "Cooking"],
    availability: "Tối thứ 2-4-6 từ 19h-21h",
    joinedDate: "2024-03-18",
  },
  {
    id: "u34",
    name: "Trịnh Văn Long",
    avatar: "📈",
    location: "Cần Thơ",
    rating: 4.8,
    totalSessions: 53,
    bio: "Chuyên gia tài chính với 16 năm kinh nghiệm. Thành thạo phân tích báo cáo tài chính!",
    offerSkills: [
      { skill: "Accounting", level: "Nâng Cao", mode: "Online" },
      { skill: "Financial Analysis", level: "Nâng Cao", mode: "Online" },
    ],
    wantSkills: ["UI Design", "Public Speaking", "Yoga"],
    availability: "Tối thứ 2-6, Sáng thứ 7",
    joinedDate: "2023-11-02",
  },
  {
    id: "u35",
    name: "Lý Thị Hương",
    avatar: "🎨",
    location: "Hải Phòng",
    rating: 4.0,
    totalSessions: 13,
    bio: "Designer UI/UX mới vào nghề. Đam mê thiết kế giao diện người dùng đẹp và thân thiện!",
    offerSkills: [
      { skill: "UI Design", level: "Cơ Bản", mode: "Online" },
      { skill: "UX Design", level: "Cơ Bản", mode: "Online" },
    ],
    wantSkills: ["Python", "Data Analysis", "French"],
    availability: "Linh hoạt, ưu tiên buổi tối",
    joinedDate: "2024-03-22",
  },
  {
    id: "u36",
    name: "Đinh Văn Tùng",
    avatar: "🧘‍♀️",
    location: "Nha Trang",
    rating: 4.9,
    totalSessions: 47,
    bio: "Huấn luyện viên yoga Ashtanga. Chuyên về yoga truyền thống và nâng cao!",
    offerSkills: [
      { skill: "Yoga", level: "Nâng Cao", mode: "Both" },
      { skill: "Ashtanga Yoga", level: "Nâng Cao", mode: "Offline" },
    ],
    wantSkills: ["Web Design", "SEO", "Chinese"],
    availability: "Sáng sớm 5h-7h, Tối 19h-21h",
    joinedDate: "2024-01-18",
  },
  {
    id: "u37",
    name: "Mai Thị Lan",
    avatar: "📸",
    location: "Hà Nội",
    rating: 3.7,
    totalSessions: 9,
    bio: "Nhiếp ảnh gia sự kiện mới vào nghề. Đam mê chụp ảnh đám cưới và tiệc!",
    offerSkills: [
      { skill: "Photography", level: "Cơ Bản", mode: "Offline" },
      { skill: "Event Photography", level: "Cơ Bản", mode: "Offline" },
    ],
    wantSkills: ["Excel", "Marketing", "Public Speaking"],
    availability: "Cuối tuần, Sáng thứ 7",
    joinedDate: "2024-03-28",
  },
  {
    id: "u38",
    name: "Nguyễn Văn Hòa",
    avatar: "🎵",
    location: "TP. Hồ Chí Minh",
    rating: 4.5,
    totalSessions: 30,
    bio: "Giáo viên piano jazz với 6 năm kinh nghiệm. Chuyên về improvisation và harmony!",
    offerSkills: [
      { skill: "Piano", level: "Nâng Cao", mode: "Both" },
      { skill: "Jazz Piano", level: "Trung Cấp", mode: "Online" },
    ],
    wantSkills: ["UI Design", "Data Analysis", "French"],
    availability: "Tối thứ 2-4-6 từ 18h-20h",
    joinedDate: "2024-02-02",
  },
  {
    id: "u39",
    name: "Trần Thị Bích",
    avatar: "💼",
    location: "Đà Nẵng",
    rating: 3.5,
    totalSessions: 6,
    bio: "Chuyên viên marketing digital mới vào nghề. Đam mê social media marketing!",
    offerSkills: [
      { skill: "Marketing", level: "Cơ Bản", mode: "Online" },
      { skill: "Social Media", level: "Cơ Bản", mode: "Online" },
    ],
    wantSkills: ["JavaScript", "Excel", "Photography"],
    availability: "Tối thứ 3-5, Sáng thứ 7",
    joinedDate: "2024-04-03",
  },
  {
    id: "u40",
    name: "Lê Văn Sơn",
    avatar: "📊",
    location: "Cần Thơ",
    rating: 4.4,
    totalSessions: 24,
    bio: "Chuyên viên phân tích dữ liệu trong ngành y tế. Thành thạo R và Python!",
    offerSkills: [
      { skill: "Data Analysis", level: "Trung Cấp", mode: "Online" },
      { skill: "R Programming", level: "Trung Cấp", mode: "Online" },
    ],
    wantSkills: ["Spanish", "Guitar", "Cooking"],
    availability: "Tối thứ 2-6 từ 19h-21h",
    joinedDate: "2024-02-18",
  },
  {
    id: "u41",
    name: "Phạm Thị Hoa",
    avatar: "🌍",
    location: "Hải Phòng",
    rating: 4.7,
    totalSessions: 38,
    bio: "Giáo viên tiếng Đức với 7 năm kinh nghiệm. Phương pháp dạy hiện đại và hiệu quả!",
    offerSkills: [
      { skill: "German", level: "Nâng Cao", mode: "Both" },
      { skill: "Language Teaching", level: "Nâng Cao", mode: "Online" },
    ],
    wantSkills: ["React", "Excel", "Personal Training"],
    availability: "Sáng thứ 2-5, Tối thứ 3-6",
    joinedDate: "2023-12-12",
  },
  {
    id: "u42",
    name: "Đỗ Văn Tài",
    avatar: "💻",
    location: "Nha Trang",
    rating: 4.1,
    totalSessions: 16,
    bio: "Lập trình viên Java với 3 năm kinh nghiệm. Đam mê phát triển backend và microservices!",
    offerSkills: [
      { skill: "Java", level: "Trung Cấp", mode: "Online" },
      { skill: "Spring Boot", level: "Cơ Bản", mode: "Online" },
    ],
    wantSkills: ["Spanish", "Photography", "Cooking"],
    availability: "Tối thứ 2-4-6 từ 19h-21h",
    joinedDate: "2024-03-16",
  },
  {
    id: "u43",
    name: "Vũ Thị Ngọc",
    avatar: "📈",
    location: "Hà Nội",
    rating: 4.8,
    totalSessions: 51,
    bio: "Chuyên gia kế toán thuế với 14 năm kinh nghiệm. Thành thạo các quy định thuế mới nhất!",
    offerSkills: [
      { skill: "Accounting", level: "Nâng Cao", mode: "Online" },
      { skill: "Tax Accounting", level: "Nâng Cao", mode: "Online" },
    ],
    wantSkills: ["UI Design", "Public Speaking", "Yoga"],
    availability: "Tối thứ 2-6, Sáng thứ 7",
    joinedDate: "2023-11-08",
  },
  {
    id: "u44",
    name: "Ngô Văn Tùng",
    avatar: "🎨",
    location: "TP. Hồ Chí Minh",
    rating: 3.9,
    totalSessions: 10,
    bio: "Designer đồ họa với 2 năm kinh nghiệm. Chuyên về thiết kế in ấn và branding!",
    offerSkills: [
      { skill: "Graphic Design", level: "Cơ Bản", mode: "Online" },
      { skill: "Print Design", level: "Cơ Bản", mode: "Online" },
    ],
    wantSkills: ["Python", "Data Analysis", "French"],
    availability: "Linh hoạt, ưu tiên buổi tối",
    joinedDate: "2024-03-24",
  },
  {
    id: "u45",
    name: "Bùi Thị Hương",
    avatar: "🧘‍♀️",
    location: "Đà Nẵng",
    rating: 4.9,
    totalSessions: 46,
    bio: "Huấn luyện viên yoga Vinyasa. Chuyên về yoga flow và kết nối hơi thở!",
    offerSkills: [
      { skill: "Yoga", level: "Nâng Cao", mode: "Both" },
      { skill: "Vinyasa Yoga", level: "Nâng Cao", mode: "Offline" },
    ],
    wantSkills: ["Web Design", "SEO", "Chinese"],
    availability: "Sáng sớm 5h-7h, Tối 19h-21h",
    joinedDate: "2024-01-22",
  },
  {
    id: "u46",
    name: "Trịnh Văn Hải",
    avatar: "📸",
    location: "Cần Thơ",
    rating: 3.6,
    totalSessions: 7,
    bio: "Nhiếp ảnh gia sản phẩm mới vào nghề. Đam mê chụp ảnh e-commerce!",
    offerSkills: [
      { skill: "Photography", level: "Cơ Bản", mode: "Offline" },
      { skill: "Product Photography", level: "Cơ Bản", mode: "Offline" },
    ],
    wantSkills: ["Excel", "Marketing", "Public Speaking"],
    availability: "Cuối tuần, Sáng thứ 7",
    joinedDate: "2024-03-30",
  },
  {
    id: "u47",
    name: "Lý Văn Phong",
    avatar: "🎵",
    location: "Hải Phòng",
    rating: 4.4,
    totalSessions: 27,
    bio: "Giáo viên violin với 5 năm kinh nghiệm. Chuyên dạy nhạc cổ điển và contemporary!",
    offerSkills: [
      { skill: "Violin", level: "Nâng Cao", mode: "Both" },
      { skill: "Music Theory", level: "Trung Cấp", mode: "Online" },
    ],
    wantSkills: ["UI Design", "Data Analysis", "French"],
    availability: "Tối thứ 2-4-6 từ 18h-20h",
    joinedDate: "2024-02-08",
  },
  {
    id: "u48",
    name: "Đinh Thị Bích",
    avatar: "💼",
    location: "Nha Trang",
    rating: 3.4,
    totalSessions: 5,
    bio: "Chuyên viên content marketing mới vào nghề. Đam mê viết blog và copywriting!",
    offerSkills: [
      { skill: "Content Writing", level: "Cơ Bản", mode: "Online" },
      { skill: "Blog Writing", level: "Cơ Bản", mode: "Online" },
    ],
    wantSkills: ["JavaScript", "Excel", "Photography"],
    availability: "Tối thứ 3-5, Sáng thứ 7",
    joinedDate: "2024-04-05",
  },
  {
    id: "u49",
    name: "Mai Văn Hùng",
    avatar: "🧘‍♀️",
    location: "Hà Nội",
    rating: 4.9,
    totalSessions: 55,
    bio: "Huấn luyện viên yoga Yin. Chuyên về yoga thư giãn và phục hồi!",
    offerSkills: [
      { skill: "Yoga", level: "Nâng Cao", mode: "Both" },
      { skill: "Yin Yoga", level: "Nâng Cao", mode: "Offline" },
    ],
    wantSkills: ["Web Design", "Chinese", "Video Editing"],
    availability: "Sáng thứ 2-6 từ 7h-9h",
    joinedDate: "2023-11-28",
  },
  {
    id: "u50",
    name: "Nguyễn Văn Dũng",
    avatar: "📊",
    location: "TP. Hồ Chí Minh",
    rating: 4.3,
    totalSessions: 22,
    bio: "Chuyên viên phân tích dữ liệu trong ngành logistics. Thành thạo Tableau và SQL!",
    offerSkills: [
      { skill: "Data Analysis", level: "Trung Cấp", mode: "Online" },
      { skill: "Tableau", level: "Trung Cấp", mode: "Online" },
    ],
    wantSkills: ["Spanish", "Guitar", "Cooking"],
    availability: "Tối thứ 2-6 từ 19h-21h",
    joinedDate: "2024-02-22",
  },
];

export interface Review {
  id: string;
  fromUser: string;
  fromAvatar: string;
  skill: string;
  rating: number;
  comment: string;
  date: string;
}

export const mockReviews: Review[] = [
  {
    id: "r1",
    fromUser: "Trần Minh Quân",
    fromAvatar: "🎸",
    skill: "JavaScript",
    rating: 5,
    comment: "Chị Giang dạy cực kỳ dễ hiểu! Những khái niệm React phức tạp được chị giải thích một cách rất dễ nắm bắt. Rất đáng để học!",
    date: "2024-10-01",
  },
  {
    id: "r2",
    fromUser: "Lê Thảo Vy",
    fromAvatar: "🧘‍♀️",
    skill: "Guitar",
    rating: 5,
    comment: "Anh Quân rất kiên nhẫn và biết cách khiến việc học guitar trở nên thú vị ngay từ buổi đầu. Mong chờ những buổi học tiếp theo!",
    date: "2024-09-28",
  },
  {
    id: "r3",
    fromUser: "Phạm Tuấn Anh",
    fromAvatar: "📸",
    skill: "Excel",
    rating: 5,
    comment: "Chị Vy am hiểu Excel ở trình độ chuyên sâu. Chị dạy mình những công thức nâng cao giúp tiết kiệm được hàng giờ làm việc!",
    date: "2024-09-25",
  },
  {
    id: "r4",
    fromUser: "Đỗ Thu Hằng",
    fromAvatar: "🎨",
    skill: "Photography",
    rating: 4,
    comment: "Buổi học rất hay! Anh Tuấn Anh chia sẻ nhiều kỹ thuật chụp chân dung hữu ích. Lần sau muốn học thêm về kỹ thuật ánh sáng.",
    date: "2024-09-20",
  },
  {
    id: "r5",
    fromUser: "Vũ Đức Long",
    fromAvatar: "💼",
    skill: "UI Design",
    rating: 5,
    comment: "Quy trình thiết kế của chị Hằng rất bài bản và chuyên nghiệp. Mình học được nhiều mẹo thực tế có thể áp dụng ngay vào dự án!",
    date: "2024-09-18",
  },
];

export type SessionStatus = "ĐANG CHỜ" | "ĐÃ XÁC NHẬN" | "ĐÃ HỦY" | "ĐÃ HOÀN THÀNH" | "TRANH CHẤP";

export interface Session {
  id: string;
  teacher: UserProfile;
  learner: UserProfile;
  skill: string;
  startTime: string;
  duration: number;
  mode: "Online" | "Offline";
  location: string;
  status: SessionStatus;
  editsAmount: number;
}

export const mockSessions: Session[] = [
  {
    id: "s1",
    teacher: mockUsers[0],
    learner: mockUsers[1],
    skill: "React",
    startTime: "2024-10-15T19:00:00",
    duration: 60,
    mode: "Online",
    location: "Zoom",
    status: "ĐÃ XÁC NHẬN",
    editsAmount: 10,
  },
  {
    id: "s2",
    teacher: mockUsers[1],
    learner: mockUsers[2],
    skill: "Guitar",
    startTime: "2024-10-16T18:00:00",
    duration: 90,
    mode: "Offline",
    location: "Austin Music Studio",
    status: "ĐANG CHỜ",
    editsAmount: 15,
  },
  {
    id: "s3",
    teacher: mockUsers[2],
    learner: mockUsers[0],
    skill: "Yoga",
    startTime: "2024-10-10T08:00:00",
    duration: 60,
    mode: "Online",
    location: "Google Meet",
    status: "ĐÃ HOÀN THÀNH",
    editsAmount: 10,
  },
];

export interface Transaction {
  id: string;
  date: string;
  sessionRef: string;
  type: "CREDIT" | "DEBIT" | "PURCHASE";
  amount: number;
  balanceAfter: number;
  description: string;
}

export const mockTransactions: Transaction[] = [
  {
    id: "t1",
    date: "2024-10-10T09:00:00",
    sessionRef: "s3",
    type: "CREDIT",
    amount: 10,
    balanceAfter: 150,
    description: "Dạy Yoga cho Nguyễn Hương Giang",
  },
  {
    id: "t2",
    date: "2024-10-09T14:00:00",
    sessionRef: "—",
    type: "PURCHASE",
    amount: 50,
    balanceAfter: 140,
    description: "Mua gói 50 Edits",
  },
  {
    id: "t3",
    date: "2024-10-08T19:30:00",
    sessionRef: "s4",
    type: "DEBIT",
    amount: -10,
    balanceAfter: 90,
    description: "Học JavaScript từ Nguyễn Hương Giang",
  },
  {
    id: "t4",
    date: "2024-10-05T16:00:00",
    sessionRef: "s5",
    type: "CREDIT",
    amount: 10,
    balanceAfter: 100,
    description: "Dạy tiếng Tây Ban Nha cho Đỗ Thu Hằng",
  },
];
